services:
  - type: web
    name: sales-management-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
