services:
  - type: web
    name: sales-management-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    buildFilter:
      paths:
      - package.json
      - package-lock.json
      - src/**
      - public/**
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
